image: Visual Studio 2017
clone_folder: c:\projects\sample
configuration: Release

environment:
    matrix:
    - platform: cygwin64
      COMPILER: cygwin
      CYGWIN_NOWINPATH: yes
      CYGSH: C:\cygwin64\bin\bash -c
    - platform: Win64
      COMPILER: vs
      VCPKG_ROOT: C:\projects\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-physycom


install:
  - if [%COMPILER%]==[vs] cinst cmake ninja
  - if [%COMPILER%]==[vs] SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - if [%COMPILER%]==[vs] call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
  - if [%COMPILER%]==[cygwin] SET "PATH=C:\cygwin64\bin;C:\cygwin64\usr\bin;%PATH%"
  - if [%COMPILER%]==[cygwin] SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - git submodule -q update --init --recursive
  - SET WORKSPACE="C:\projects"
  - cd %WORKSPACE%\
  - mkdir cygwin-downloads
  - ps: if($env:COMPILER -eq "cygwin") { Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile C:\projects\cygwin-setup.exe }
  - if [%COMPILER%]==[cygwin] C:\projects\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --root C:\cygwin64 --local-package-dir C:\projects\cygwin-downloads --packages gcc-g++,libboost-devel,cmake,libfltk-devel,libglut-devel,libGL-devel,libGLU-devel,fluid,libjpeg-devel,libXi-devel,libXmu-devel
  - git clone https://github.com/physycom/sysconfig
  - if [%COMPILER%]==[vs] git clone https://github.com/Microsoft/vcpkg
  - if [%COMPILER%]==[vs] copy %WORKSPACE%\sysconfig\cmake\%VCPKG_DEFAULT_TRIPLET%.cmake %WORKSPACE%\vcpkg\triplets\
  - if [%COMPILER%]==[vs] cd %VCPKG_ROOT%
  - if [%COMPILER%]==[vs] bootstrap-vcpkg.bat
  - if [%COMPILER%]==[vs] vcpkg integrate install
# - if [%COMPILER%]==[vs] vcpkg install ...
  - cd %WORKSPACE%\sample\
  - mkdir build
  - cd build

build_script:
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake .. -G "Unix Makefiles"'
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake --build .'
  - if [%COMPILER%]==[vs] cmake .. -G "Visual Studio 15 2017 Win64" "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET%"
  - if [%COMPILER%]==[vs] cmake --build . --config Release
